//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeInteropTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public Article()
        {
            this.Categories = new HashSet<Category>();
            this.Names = new HashSet<Name>();
        }
    
        public string ArticleId { get; set; }
        public string ArticleText { get; set; }
        public string ArticleUrl { get; set; }
        public string ArticleTitle { get; set; }
        public string ArticleSource { get; set; }
        public string ArticleDescription { get; set; }
    
        public virtual ICollection<Category> Categories { get; set; }
        public virtual ICollection<Name> Names { get; set; }
    }
}
